"""
Django settings for chat_project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(dotenv_path: Path) -> None:
    if not dotenv_path.exists():
        return

    for raw_line in dotenv_path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip("'\"")

        if key and key not in os.environ:
            os.environ[key] = value


_load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-dev-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() == "true"

def _split_csv(value: str) -> list[str]:
    return [item.strip() for item in value.split(",") if item.strip()]


ALLOWED_HOSTS = _split_csv(
    os.getenv(
        "DJANGO_ALLOWED_HOSTS",
        "127.0.0.1,localhost,ntchat-gve8eseuhqf0f4hg.switzerlandnorth-01.azurewebsites.net",
    )
)

CSRF_TRUSTED_ORIGINS = _split_csv(
    os.getenv(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        "https://ntchat-gve8eseuhqf0f4hg.switzerlandnorth-01.azurewebsites.net",
    )
)

azure_hostname = os.getenv("WEBSITE_HOSTNAME")
if azure_hostname and azure_hostname not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(azure_hostname)

azure_origin = f"https://{azure_hostname}" if azure_hostname else None
if azure_origin and azure_origin not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(azure_origin)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounts_app',
    'messages_app',
    'notifications_app',
    'rooms_app',
    'profiles_app',
    'staff_panel_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'chat_project.urls'

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chat_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

azure_connection_string = os.getenv("AZURE_POSTGRESQL_CONNECTIONSTRING", "")
parsed_connection = urlparse(azure_connection_string) if azure_connection_string else None
connection_options = (
    parse_qs(parsed_connection.query) if parsed_connection and parsed_connection.query else {}
)

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv(
            "DB_NAME",
            parsed_connection.path.lstrip("/") if parsed_connection and parsed_connection.path else "ntchat-database",
        ),
        "USER": os.getenv(
            "DB_USER",
            parsed_connection.username if parsed_connection and parsed_connection.username else "SHRNiko",
        ),
        "PASSWORD": os.getenv(
            "DB_PASSWORD",
            parsed_connection.password if parsed_connection and parsed_connection.password else "",
        ),
        "HOST": os.getenv(
            "DB_HOST",
            parsed_connection.hostname if parsed_connection and parsed_connection.hostname else "nt-server.postgres.database.azure.com",
        ),
        "PORT": os.getenv(
            "DB_PORT",
            str(parsed_connection.port) if parsed_connection and parsed_connection.port else "5432",
        ),
        "OPTIONS": {
            "sslmode": os.getenv(
                "DB_SSLMODE",
                connection_options.get("sslmode", ["require"])[0],
            ),
        },
    }
}

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG and bool(azure_hostname)

AUTH_USER_MODEL = "accounts_app.ChatUser"
LOGIN_REDIRECT_URL = "room_list"
LOGOUT_REDIRECT_URL = "room_list"

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}
