# Generated by Django 6.0.2 on 2026-05-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0003_tag_room_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='posting_policy',
            field=models.CharField(choices=[('members', 'Any room member'), ('moderators', 'Room moderators only'), ('staff', 'Staff only')], default='members', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private (members only)'), ('staff', 'Staff Only')], default='public', max_length=20),
        ),
    ]
