# Generated by Django 6.0.2 on 2026-06-20 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0002_profile_avatar'),
        ('rooms_app', '0004_room_posting_policy_room_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='join_policy',
            field=models.CharField(choices=[('open', 'Anyone can join'), ('invite', 'Invite required')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='RoomInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_room_invitations', to='profiles_app.profile')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_invitations', to='profiles_app.profile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='rooms_app.room')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('room', 'invitee')},
            },
        ),
    ]
