# Generated by Django 6.0.2 on 2026-02-12 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts_app.chatuser')),
                ('nickname', models.CharField(max_length=30, unique=True)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
